"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import environ # <-- Importamos la nueva librería

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- AÑADE ESTAS DOS LÍNEAS ---
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8ph(t+8uc@+as)%adyul!&c^s)1ywu7b$7(b2ubarf-sh3g21z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Has puesto False, lo cual es correcto para producción

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles', # Asegúrate que está aquí
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap5',
    'canchas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Si tuvieras una carpeta 'templates' a nivel de proyecto (C:\viejopadel\config\templates)
            # la añadirías aquí: BASE_DIR / "templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'


USE_L10N = True
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/' # URL para acceder a los archivos estáticos en el navegador

# ------------ MODIFICACIÓN IMPORTANTE AQUÍ ------------
# Directorio donde `collectstatic` copiará todos los archivos estáticos para producción.
# DEBE ser una ruta absoluta a una carpeta que NO esté ya en STATICFILES_DIRS.
# Django creará esta carpeta si no existe.
# Con tu BASE_DIR, esto será: C:\viejopadel\config\staticfiles\
STATIC_ROOT = BASE_DIR / "staticfiles"

# Opcional: Lista de directorios donde Django buscará archivos estáticos
# además de la carpeta 'static' de cada app.
# Si tienes una carpeta 'static' a nivel de proyecto (ej: C:\viejopadel\config\static\)
# la añades aquí.
STATICFILES_DIRS = [
    # BASE_DIR / "static", # Descomenta y crea esta carpeta si tienes archivos estáticos globales.
                           # Por ejemplo: C:\viejopadel\config\static\
                           # La app 'canchas' tiene 'canchas/static/', que ya es encontrada.
]
# ------------ FIN DE LA MODIFICACIÓN IMPORTANTE ------------

# MEDIA_ROOT = os.path.join(BASE_DIR, 'static') # Esta línea era incorrecta para MEDIA_ROOT y redundante, la elimino.

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'cancha-list'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Media files (Archivos subidos por el usuario)
MEDIA_URL = '/media/'
# Con tu BASE_DIR, esto será: C:\viejopadel\config\mediafiles\
MEDIA_ROOT = BASE_DIR / "mediafiles"









# ==============================================================================
# CONFIGURACIÓN DE ENVÍO DE EMAIL (PARA RESETEO DE CONTRASEÑA, ETC.)
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Leemos las credenciales de nuestro archivo seguro .env
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# Opcional pero recomendado: para que el remitente en los correos de error se vea bien.
SERVER_EMAIL = DEFAULT_FROM_EMAIL


SITE_ID = 1