# Generated by Django 5.2 on 2025-04-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cancha Principal, Pista 1 Tenis', max_length=100, unique=True, verbose_name='Nombre de la Cancha')),
                ('tipo_deporte', models.CharField(choices=[('futbol_5', 'Fútbol 5'), ('futbol_7', 'Fútbol 7'), ('futbol_11', 'Fútbol 11'), ('tenis', 'Tenis'), ('padel', 'Pádel'), ('basquet', 'Básquetbol'), ('voley', 'Vóley'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Deporte')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales como tipo de superficie, si es techada, etc.', null=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, help_text='Descripción de dónde se encuentra dentro del complejo.', max_length=200, null=True, verbose_name='Ubicación')),
                ('esta_activa', models.BooleanField(default=True, help_text='Desmarcar si la cancha no está disponible temporalmente (mantenimiento, etc.)', verbose_name='Está Activa')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponibles', to='canchas.cancha', verbose_name='Cancha')),
            ],
            options={
                'verbose_name': 'Horario Disponible',
                'verbose_name_plural': 'Horarios Disponibles',
                'ordering': ['cancha', 'dia_semana', 'hora_inicio'],
                'unique_together': {('cancha', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
