# Generated by Django 5.2 on 2025-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre_reserva',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Reserva'),
        ),
    ]
