# Generated by Django 5.2 on 2025-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_reserva_nombre_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva_origen',
            field=models.CharField(choices=[('unico', 'Único'), ('mensual', 'Mensual')], default='unico', help_text='Indica si esta reserva se creó como única o parte de un bloque mensual/diario.', max_length=10, verbose_name='Tipo Origen'),
        ),
    ]
