# Generated by Django 5.2 on 2025-04-10 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_reserva_tipo_reserva_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Egreso')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Gasto')),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios (Luz, Agua, Gas)'), ('personal', 'Personal / Sueldos'), ('limpieza', 'Limpieza'), ('marketing', 'Marketing / Publicidad'), ('impuestos', 'Impuestos / Tasas'), ('insumos', 'Insumos Deportivos'), ('proveedores', 'Proveedores Varios'), ('administrativo', 'Gasto Administrativo'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Categoría')),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_asociados', to='canchas.cancha', verbose_name='Cancha Asociada (Opcional)')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_asociados', to='canchas.reserva', verbose_name='Reserva Asociada (Opcional)')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Ingreso')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.CharField(help_text='Ej: Pago reserva, Venta extra, Abono mensual', max_length=255, verbose_name='Descripción')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_asociados', to='canchas.reserva', verbose_name='Reserva Asociada (Opcional)')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha', '-pk'],
            },
        ),
    ]
