# Generated by Django 5.2 on 2025-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_egreso_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio cobrado por este turno específico (sin extras).', max_digits=10, null=True, verbose_name='Precio de la Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva_origen',
            field=models.CharField(choices=[('unico', 'Único'), ('mensual', 'Mensual')], default='unico', max_length=10, verbose_name='Tipo Origen'),
        ),
    ]
