# Generated by Django 5.2 on 2025-04-11 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0007_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ingresos')),
                ('total_egresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Egresos')),
                ('total_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ventas Extras')),
            ],
            options={
                'verbose_name': 'Resumen Diario',
                'verbose_name_plural': 'Resúmenes Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ingresos')),
                ('total_egresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Egresos')),
                ('total_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ventas Extras')),
            ],
            options={
                'verbose_name': 'Resumen Mensual',
                'verbose_name_plural': 'Resúmenes Mensuales',
                'ordering': ['-año', '-mes'],
                'unique_together': {('año', 'mes')},
            },
        ),
    ]
