# Generated by Django 5.2 on 2025-04-11 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0008_resumendiario_resumenmensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Número de unidades vendidas.', verbose_name='Cantidad Vendida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del extra en el momento de la venta.', max_digits=10, verbose_name='Precio Unitario')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='canchas.extra', verbose_name='Producto Extra')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_asociadas', to='canchas.ingreso', verbose_name='Ingreso Asociado')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='canchas.reserva', verbose_name='Reserva Asociada (Opcional)')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_asociados', to='canchas.venta', verbose_name='Venta Asociada (Opcional)'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad disponible para la venta.', verbose_name='Cantidad en Stock')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Actualización')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='canchas.extra', verbose_name='Producto Extra')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['extra__nombre'],
                'unique_together': {('extra',)},
            },
        ),
    ]
