# Generated by Django 5.2 on 2025-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0009_venta_ingreso_venta_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
