# Generated by Django 5.2 on 2025-04-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0010_extra_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_por_venta', to='canchas.extra', verbose_name='Producto Vendido (Opcional)'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='cancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_asociados_cancha', to='canchas.cancha', verbose_name='Cancha Asociada (Opcional)'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_asociados_reserva', to='canchas.reserva', verbose_name='Reserva Asociada (Opcional)'),
        ),
    ]
