# Generated by Django 5.2 on 2025-04-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0011_egreso_producto_alter_egreso_cancha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='stock',
        ),
    ]
