# Generated by Django 5.2 on 2025-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0012_remove_extra_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Método de Pago'),
        ),
    ]
