# Generated by Django 5.2 on 2025-04-28 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0014_venta_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picadito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Fútbol Jueves Noche', 'Amistoso Sábado Tarde'", max_length=150, verbose_name='Nombre/Descripción del Picadito')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Picadito')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio (Aprox)')),
                ('jugadores', models.TextField(blank=True, help_text='Ingresa un nombre por línea.', verbose_name='Lista de Jugadores')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picaditos', to='canchas.cancha', verbose_name='Cancha Asociada (Opcional)')),
            ],
            options={
                'verbose_name': 'Picadito',
                'verbose_name_plural': 'Picaditos',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
