# Generated by Django 5.2 on 2025-04-28 14:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0015_picadito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picadito',
            name='jugadores',
        ),
        migrations.CreateModel(
            name='ParticipantePicadito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=100, verbose_name='Nombre del Jugador')),
                ('costo_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total de los items consumidos por este jugador (considerando descuentos)', max_digits=10, verbose_name='Costo Calculado')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('items_consumidos', models.ManyToManyField(blank=True, to='canchas.extra', verbose_name='Items Consumidos')),
                ('picadito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='canchas.picadito', verbose_name='Picadito')),
            ],
            options={
                'verbose_name': 'Participante de Picadito',
                'verbose_name_plural': 'Participantes de Picaditos',
                'ordering': ['nombre_jugador'],
                'unique_together': {('picadito', 'nombre_jugador')},
            },
        ),
    ]
