# Generated by Django 5.2 on 2025-04-28 14:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0016_remove_picadito_jugadores_participantepicadito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantepicadito',
            name='costo_calculado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total de los items consumidos por este jugador (considerando reglas especiales)', max_digits=10, verbose_name='Costo Calculado'),
        ),
    ]
