# Generated by Django 5.2 on 2025-04-29 13:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0017_alter_participantepicadito_costo_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepicadito',
            name='costo_cancha',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto correspondiente a la cancha asignado a este jugador.', max_digits=10, verbose_name='Costo Cancha Asignado'),
        ),
        migrations.AddField(
            model_name='participantepicadito',
            name='items_con_descuento',
            field=models.ManyToManyField(blank=True, related_name='participantes_con_descuento', to='canchas.extra', verbose_name='Items Consumidos con Descuento'),
        ),
    ]
