# Generated by Django 5.2 on 2025-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0018_participantepicadito_costo_cancha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('pendiente_pago', 'Pendiente de Pago'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva_origen',
            field=models.CharField(choices=[('diario', 'Diario'), ('mensual', 'Mensual')], default='diario', max_length=10, verbose_name='Tipo Origen'),
        ),
    ]
