# Generated by Django 5.2 on 2025-06-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0019_alter_reserva_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente (Si no es usuario)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente (Si no es usuario)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente (Si no es usuario)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva_origen',
            field=models.CharField(choices=[('diario', 'Diario (Empleado/Admin)'), ('mensual', 'Mensual (Empleado/Admin)'), ('cliente', 'Cliente Web')], default='diario', max_length=10, verbose_name='Tipo Origen'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrado (Opcional)'),
        ),
    ]
