# Generated by Django 5.2 on 2025-06-03 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0020_reserva_cliente_email_reserva_cliente_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_telefono',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva_origen',
            field=models.CharField(choices=[('diario', 'Diario'), ('mensual', 'Mensual')], default='diario', max_length=10, verbose_name='Tipo Origen'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
