# Generated by Django 5.2 on 2025-06-11 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0022_venta_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDeCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Cierre')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total Cerrado')),
                ('cantidad_ventas', models.PositiveIntegerField(verbose_name='Cantidad de Ventas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_de_caja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Historial de Cierres de Caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cierre_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_incluidas', to='canchas.cierredecaja', verbose_name='Cierre de Caja Asociado'),
        ),
    ]
