# Generated by Django 5.2 on 2025-06-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0025_venta_cierre_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cierre_caja',
        ),
    ]
