# Generated by Django 5.2 on 2025-06-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0026_remove_venta_cierre_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cierre_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_incluidas', to='canchas.cierredecaja', verbose_name='Cierre de Caja Asociado'),
        ),
    ]
