# Generated by Django 5.2 on 2025-06-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0027_venta_cierre_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierredecaja',
            name='cantidad_ventas',
        ),
        migrations.RemoveField(
            model_name='cierredecaja',
            name='monto_total',
        ),
        migrations.AddField(
            model_name='cierredecaja',
            name='cantidad_movimientos',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad de Movimientos'),
        ),
        migrations.AddField(
            model_name='cierredecaja',
            name='total_egresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Egresos'),
        ),
        migrations.AddField(
            model_name='cierredecaja',
            name='total_ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Ingresos'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='cierre_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_incluidos', to='canchas.cierredecaja', verbose_name='Cierre de Caja Asociado'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='cierre_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_incluidos', to='canchas.cierredecaja', verbose_name='Cierre de Caja Asociado'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
